### ISSUE TITLE
change context to order

### ISSUE THREAD

**Issue by ligi** [efdevcon/pretix-attestation-placeholder-plugin#21]
context was changed from 'order' to 'position' - but this introduces a problem that we cannot send the attestation link to the attendees where order-creator-email == attendee email as:
![image](https://user-images.githubusercontent.com/111600/115011749-4c35ed00-9eaf-11eb-86b1-4834195aa910.png)

**Comment by Nurts** [comment]
Hi @ligi , I tried to change the context. But even though it works for the person who orders the tickets. Other attendees would also receive the same attestation link as the person who ordered, because I did not find a way to get the receivers email inside `render` function.
Thus, I was thinking of creating another placeholder, with `order` context, which would only send the attestation link of the person who orders. Do you think this is a good idea?
